### ISSUE TITLE
Event Attachments via the Public calendar API

### ISSUE THREAD

**Issue by digistorm-developer** [TheAlphaSchoolSystemPTYLTD/public-calendar-and-notices#4]
Hi,

Just wondering what might cause some attachments to come through the API with neither a deep link or a URL? Is this something that requires configuring the events differently from the users end? See example event below. Any help is appreciated.

```
{
        "location": "",
        "attachment": {
            "file_size": 125606,
            "deep_link": "",
            "file_name": "2019TouchBreak-upInvitation.pdf"
        },
        "cat_num": 4,
        "url_text": "",
        "day_time_desc": "Tue 15 Oct 2019 at 3:30pm (End 5:00pm)",
        "campus_code": "",
        "cat_desc": "Sport",
        "dayFlag": "",
        "summary": "Girls Touch Break up will be held on the Junior School Oval and Pavilion.",
        "has_attachment": true,
        "description": "Girls Touch Break up will be held on the Junior School Oval and Pavilion.",
        "single_day": true,
        "year_groups": {
            "7": 7,
            "8": 8,
            "9": 9,
            "10": 10,
            "11": 11,
            "12": 12
        },
        "source": "school",
        "title": "Girls Touch Break up",
        "start": "2019-10-15 15:30:00",
        "end": "2019-10-15 17:00:00",
        "id": 68828,
        "url_link": "",
        "feed": "School Calendar",
        "all_day": false
    }
```

Thanks

Chris Love
Digistorm

**Comment by bradftass** [comment]
Hi Chris, this functionality does not appear to be in operation for the Public Calendar, though it is accessible for the School Calendar & Events API.
https://github.com/TheAlphaSchoolSystemPTYLTD/school-calendar-and-notices
getStudentCalendar
getTeacherCalendar

I will raise this internally to see if it can be added to the roadmap.

**Comment by scottetass** [comment]
Hi,

url_text and url_link is populated by the event creator, so if they haven't put anything in, then there is nothing to return.

As for deep_link field for attachments, it appears to be working as expected now. Given this issue is very old, I suspect the functionality has since been fixed. Please try again and raise a new issue if the problem still exists.

Thanks, Scott
